-- Optional local test user. Replace the password with a real BCrypt hash generated by the backend auth module later.
-- INSERT INTO user (username, password, nickname, role)
-- VALUES ('testuser', '<BCrypt hash generated later>', '测试用户', 'USER');

INSERT INTO project (
    user_id,
    name,
    description,
    tech_stack,
    role,
    highlights,
    difficulties
)
VALUES (
    1,
    '高并发营销系统',
    '该项目面向营销活动场景，支持优惠券发放、抽奖和秒杀等业务能力。',
    'Spring Boot, MySQL, Redis, RabbitMQ',
    '负责优惠券秒杀模块和库存扣减逻辑',
    '使用 Redis 预扣库存，结合 MQ 异步削峰。',
    '需要处理超卖、重复消费、缓存一致性和接口限流等问题。'
);
