package com.codecoach.module.ai.enums;

public enum AiRequestType {

    INTERVIEW_FIRST_QUESTION,
    INTERVIEW_FEEDBACK_NEXT_QUESTION,
    INTERVIEW_REPORT,
    QUESTION_FIRST_QUESTION,
    QUESTION_FEEDBACK_NEXT_QUESTION,
    QUESTION_REPORT
}
